version: '3.4'
services:
  db:
    image: jsurf/rpi-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    volumes:
      - /mnt/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  passbolt:
    image: tchak2k/docker-passbolt:rpi4
    tty: true

    depends_on:
      - db
    environment:
      - APP_FULL_BASE_URL=${APP_FULL_BASE_URL}
      - DATASOURCES_DEFAULT_HOST=${DATASOURCES_DEFAULT_HOST}
      - DATASOURCES_DEFAULT_USERNAME=${DATASOURCES_DEFAULT_USERNAME}
      - DATASOURCES_DEFAULT_PASSWORD=${DATASOURCES_DEFAULT_PASSWORD}
      - DATASOURCES_DEFAULT_DATABASE=${DATASOURCES_DEFAULT_DATABASE}
      - DATASOURCES_DEFAULT_PORT=${DATASOURCES_DEFAULT_PORT}
      - PASSBOLT_REGISTRATION_PUBLIC=${PASSBOLT_REGISTRATION_PUBLIC}
    volumes:
      - /mnt/passbolt/gpg:/var/www/passbolt/config/gpg
      - /mnt/passbolt/images:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443
